import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Tracks from "../components/Tracks";
import Script from "next/script";
import React from "react";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Probando Spotify</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Script></Script>

			<main className={styles.main}>
				<h1 className={styles.title}>
					David <a href="https://nextjs.org">Spotify React</a>
				</h1>
				<Tracks />
			</main>
		</div>
	);
};

export default Home;
